language: php
sudo: false
cache:
  directories:
    - $HOME/.composer/cache/files

matrix:
  include:
    - php: 5.3
      env: 
        - DEPS="low"
    - php: 5.4
    - php: 5.5
    - php: 5.6
      env: 
        - DEPS="lock"
    - php: 7.0
      env: 
        - TEST_COVERAGE=true
    - php: 7.0
      env:
        - XDEBUG_DISABLE=true
    - php: 7.1
    - php: 7.1
      env:
        - XDEBUG_DISABLE=true
    - php: hhvm
  allow_failures:
    - php: hhvm
  fast_finish: true

install:
  - if [[ $XDEBUG_DISABLE ]]; then phpenv config-rm xdebug.ini; fi
  - if [[ $TEST_COVERAGE ]]; then PHPUNIT_FLAGS="--coverage-clover ./build/logs/clover.xml"; fi

  - if [[ $DEPS == "low" ]]; then composer update --prefer-lowest --prefer-dist --prefer-stable --no-interaction; fi
  - if [[ $DEPS == "lock" ]]; then composer install --prefer-dist --no-interaction; fi
  - if [[ -z $DEPS ]]; then composer update --prefer-dist --prefer-stable --no-interaction; fi

script:
  - bin/phpunit -v $PHPUNIT_FLAGS
  - composer install --no-dev --no-interaction
  - src/Paraunit/Bin/paraunit run nothing

after_success:
  - if [[ $TEST_COVERAGE ]]; then php bin/coveralls -v; fi
  - if [[ $TEST_COVERAGE ]]; then wget https://scrutinizer-ci.com/ocular.phar && php ocular.phar code-coverage:upload --format=php-clover ./build/logs/clover.xml; fi
  - if [[ $TEST_COVERAGE ]]; then bin/test-reporter; fi

before_deploy:
  - composer update --no-dev
  - curl -LSs https://box-project.github.io/box2/installer.php | php
  - php box.phar build
  - echo $DECRYPT_KEY | gpg --passphrase-fd 0 contrib/ParaunitSigningKeys.asc.gpg && gpg --batch --yes --import contrib/ParaunitSigningKeys.asc
  - echo $SIGN_KEY | gpg --passphrase-fd 0 -u E4F5798D --armor --detach-sig paraunit.phar 
  - gpg --verify paraunit.phar.asc paraunit.phar

deploy:
  provider: releases
  api_key: $GITHUB_API_KEY
  file:
    - paraunit.phar
    - paraunit.phar.asc
  skip_cleanup: true
  on:
    tags: true
    php: 5.3
